In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [2]:
#读取数据
X=pd.read_csv('cym_data_pca.csv',index_col='id')
# X = np.array([[-10,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])  #导入数据，维度为4
# X = np.array([[10000,1,1,1], [10000,3,4,5],[10000,20,200,2000]])  #导入数据，维度为4
print(X)

          diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                          
842302            1        17.99         10.38          122.80     1001.0   
842517            1        20.57         17.77          132.90     1326.0   
84300903          1        19.69         21.25          130.00     1203.0   
84348301          1        11.42         20.38           77.58      386.1   
84358402          1        20.29         14.34          135.10     1297.0   
...             ...          ...           ...             ...        ...   
926424            1        21.56         22.39          142.00     1479.0   
926682            1        20.13         28.25          131.20     1261.0   
926954            1        16.60         28.08          108.30      858.1   
927241            1        20.60         29.33          140.10     1265.0   
92751             0         7.76         24.54           47.92      181.0   

In [3]:
#pca降维
pca = PCA(n_components=4)   #降到2维
pca.fit(X)                  #训练
newX=pca.fit_transform(X)   #降维后的数据
# PCA(copy=True, n_components=2, whiten=False)
print("原始pca,输出贡献率",pca.explained_variance_ratio_)  #输出贡献率
print("降维后数据",newX)                  #输出降维后的数据
print("具有最大方差的成分",pca.components_)
print("所保留的n个成分各自的方差",pca.explained_variance_)
# print("所保留的n个成分各自的方差百分比",pca.explained_variance_ratio_)
# print("所保留的成分个数n",pca.n_components_)
print("噪声方差大小",pca.noise_variance_)
# print("特征均值",pca.mean_)
# print("转换为原始数据",pca.inverse_transform(newX))
# print("转换为降维数据",pca.transform(X))

原始pca,输出贡献率 [9.82044441e-01 1.61764823e-02 1.55751474e-03 1.20993454e-04]
降维后数据 [[1160.14274385 -293.91753487   48.57838829   -8.71977365]
 [1269.12259735   15.63019385  -35.39433793   17.86050902]
 [ 995.7940818    39.15672295   -1.7099218     4.19611699]
 ...
 [ 314.50204562   47.55342261  -10.44324763   -9.77775872]
 [1124.85828992   34.12921837  -19.74220047  -23.65584083]
 [-771.52771076  -88.64311299   23.88898053    2.54937566]]
具有最大方差的成分 [[ 5.32491176e-04  5.08623135e-03  2.19657036e-03  3.50763253e-02
   5.16826394e-01  4.23694648e-06  4.05260057e-05  8.19399513e-05
   4.77807747e-05  7.07804557e-06 -2.62155144e-06  3.13742465e-04
  -6.50983758e-05  2.23634120e-03  5.57271577e-02 -8.05645804e-07
   5.51918267e-06  8.87094529e-06  3.27915015e-06 -1.24101786e-06
  -8.54529271e-08  7.15473171e-03  3.06736655e-03  4.94576389e-02
   8.52063272e-01  6.42005767e-06  1.01275948e-04  1.68928633e-04
   7.36658167e-05  1.78986335e-05  1.61356430e-06]
 [-2.20205422e-04  9.28705507e-03 -2.

In [4]:
#增量PCA(IPCA)
#使用np.array_split（）方法的IPCA
from sklearn.decomposition import IncrementalPCA
#读取数据
X=pd.read_csv('cym_data_pca.csv',index_col='id')
# print(X)
n_batches = 100
inc_pca = IncrementalPCA(n_components=4)
for X_batch in np.array_split(X, n_batches):
    inc_pca.partial_fit(X_batch)
X_mnist_reduced = inc_pca.transform(X)
print("输出贡献率",inc_pca.explained_variance_ratio_)  #输出贡献率
print("降维后数据",X_mnist_reduced)                  #输出降维后的数据
print("具有最大方差的成分",inc_pca.components_)
print("所保留的n个成分各自的方差",inc_pca.explained_variance_)
print("噪声方差大小",inc_pca.noise_variance_)

输出贡献率 [9.82044441e-01 1.61764741e-02 1.55656434e-03 1.19260331e-04]
降维后数据 [[1160.14274453 -293.91849849   48.69921365   11.58869739]
 [1269.12259758   15.63013103  -35.40953513  -18.16973133]
 [ 995.79408186   39.15672226   -1.71170263   -4.21442663]
 ...
 [ 314.50204538   47.55363243  -10.46687518    9.17823142]
 [1124.85828993   34.12903837  -19.72967046   23.87598418]
 [-771.52771147  -88.6424344    23.83457567   -3.90162968]]
具有最大方差的成分 [[ 5.32491018e-04  5.08623324e-03  2.19655257e-03  3.50763378e-02
   5.16826393e-01  4.23695123e-06  4.05260180e-05  8.19399266e-05
   4.77808016e-05  7.07805542e-06 -2.62155667e-06  3.13742461e-04
  -6.51003538e-05  2.23634132e-03  5.57271529e-02 -8.05648949e-07
   5.51916959e-06  8.87090655e-06  3.27915590e-06 -1.24102102e-06
  -8.54555437e-08  7.15473355e-03  3.06733745e-03  4.94576517e-02
   8.52063272e-01  6.42003816e-06  1.01275890e-04  1.68928486e-04
   7.36658570e-05  1.78986127e-05  1.61354749e-06]
 [-2.20230645e-04  9.28587042e-03 -2.863904

In [5]:
#随机PCA
#读取数据
X=pd.read_csv('cym_data_pca.csv',index_col='id')
# print(X)
rnd_pca = PCA(n_components=4, svd_solver="randomized")
X_reduced = rnd_pca.fit_transform(X)
print("输出贡献率",rnd_pca.explained_variance_ratio_)  #输出贡献率
print("降维后数据",X_reduced)                  #输出降维后的数据
print("具有最大方差的成分",rnd_pca.components_)
print("所保留的n个成分各自的方差",rnd_pca.explained_variance_)
print("噪声方差大小",rnd_pca.noise_variance_)

输出贡献率 [9.82044441e-01 1.61764823e-02 1.55751474e-03 1.20993454e-04]
降维后数据 [[1160.14274385 -293.91753487   48.57838829   -8.71977365]
 [1269.12259735   15.63019385  -35.39433793   17.86050902]
 [ 995.7940818    39.15672295   -1.7099218     4.19611699]
 ...
 [ 314.50204562   47.55342261  -10.44324763   -9.77775872]
 [1124.85828992   34.12921837  -19.74220047  -23.65584083]
 [-771.52771076  -88.64311299   23.88898053    2.54937566]]
具有最大方差的成分 [[ 5.32491176e-04  5.08623135e-03  2.19657036e-03  3.50763253e-02
   5.16826394e-01  4.23694648e-06  4.05260057e-05  8.19399513e-05
   4.77807747e-05  7.07804557e-06 -2.62155144e-06  3.13742465e-04
  -6.50983758e-05  2.23634120e-03  5.57271577e-02 -8.05645804e-07
   5.51918267e-06  8.87094529e-06  3.27915015e-06 -1.24101786e-06
  -8.54529271e-08  7.15473171e-03  3.06736655e-03  4.94576389e-02
   8.52063272e-01  6.42005767e-06  1.01275948e-04  1.68928633e-04
   7.36658167e-05  1.78986335e-05  1.61356430e-06]
 [-2.20205422e-04  9.28705507e-03 -2.881616

In [6]:
#核PCA(Kernel PCA)
# 读取数据
# data=pd.read_csv('cym_data_pca.csv',index_col='id')

#生成Swiss roll数据
from sklearn.datasets import make_swiss_roll
data=make_swiss_roll(n_samples=1000, noise=0.0, random_state=None)
X=data[0]
y=data[1]
#画3维图
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
ax = plt.subplot(111, projection='3d')
ax.scatter(X[:,0], X[:,1], X[:,2],c=y)
plt.show()
#kPCA
from sklearn.decomposition import KernelPCA
rbf_pca = KernelPCA(n_components = 2, kernel="rbf", gamma=0.04)
X_reduced = rbf_pca.fit_transform(X)

from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
X,y = mnist["data"],mnist["target"]

from sklearn.decomposition import KernelPCA
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
clf = Pipeline([
("kpca", KernelPCA(n_components=2)),
("log_reg", LogisticRegression())
])
param_grid = [{
"kpca__gamma": np.linspace(0.03, 0.05, 10),
"kpca__kernel": ["rbf", "sigmoid"]
}]
grid_search = GridSearchCV(clf, param_grid, cv=3)
grid_search.fit(X, y)
print(grid_search.best_params_)

<Figure size 640x480 with 1 Axes>

H:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)
H:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)


TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

In [ ]:
#PCA和T-SNE
# 读取数据
data=pd.read_csv('cym_data_pca.csv',index_col='id')
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
data_pca = PCA(n_components=20).fit_transform(data)
data_pca_tsne = TSNE(n_components=2).fit_transform(data_pca)
print("pca",data_pca)
print("tsne",data_pca_tsne)

In [ ]:
#MDS:多维标度法
# 读取数据
data=pd.read_csv('cym_data_pca.csv',index_col='id')
from sklearn.manifold import MDS
mds = MDS(n_components=3)
Xtrans = mds.fit_transform(data)
print(data)